### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AJ-Stiles**

### CODE REVIEW

**Comment by Ifycode** [comment]
So you made your changes in main this time, which is not advisable. The solution I have for you is to delete your fork and fork again. Then create a new branch before making your changes @AJ-Stiles

**Comment by AJ-Stiles** [comment]
Why is it not advisable??

**Comment by Ifycode** [comment]
@AJ-Stiles The main branch usually contains the production ready version (i.e. the finished product) of the repo.

**Comment by AJ-Stiles** [comment]
Awesome, thanks!

**Comment by Ifycode** [comment]
👍🏽👍🏽👍🏽

**Pull request closed without merging**
